account: epic
app: LND
coldstart: 'NO'
coupler_calendar: 2
date_cycle_freq_hr: 24
date_first_cycle: 200001040000
date_last_cycle: 200001050000
dt_atmos: 900
dt_runseq: 3600
envir: test_lnd
exp_case_name: lnd_test_00
fcsthr: 24
lnd_calc_snet: .true.
lnd_ic_type: custom
lnd_initial_albedo: 0.25
lnd_layout_x: 1
lnd_layout_y: 2
lnd_output_freq_sec: 21600
med_coupling_mode: ufs.nfrac.aoflux
model_ver: v2.1.0
net: landda
nprocs_analysis: 6
res: 96
run: landda
we2e_test: 'NO'
